### ISSUE TITLE
How to provide SOPS keys for decryption?

### ISSUE THREAD

**Issue by lictw** [kluctl/flux-kluctl-controller#21]
### Controller

- [ ] KluctlProject
- [X] KluctlDeployment
- [ ] KluctlMultiDeployment

### What do you want to do?

I want a way with secret (as in Flux).

**Comment by codablock** [comment]
I'm in the middle of implementing this atm. Unfortunately, the currently released controllers is still based on kluctl 2.16.x. I'll ping you here when the new release is ready.

**Comment by codablock** [comment]
@lictw v0.9.0 supportes providing SOPS keys from now on. Check the docs for details :)

**Comment by lictw** [comment]
It works, thanks!
