### ISSUE TITLE
Provide Prometheus metrics for instrumentation, monitoring and alerting

### ISSUE THREAD

**Issue by AljoschaP** [kluctl/flux-kluctl-controller#86]
### Controller

- [ ] KluctlDeployment

### Who are you?

Aljoscha, 30, Software Engineer at Hellmann Worldwide Logistics

### What do you want to do?

As a user of the controller, I would like to have metrics provided by the controller to better understand the behavior of the controller as well as to have some insight into its usage. For example, it would be really interesting to use the metrics of the controller (e.g. number of deployments, deployment duration, number of changes) to understand how the teams use the controller for their deployments (Number of deployments per team, small or big changes, etc.). Because Prometheus is the de facto standard, I think it makes sense to integrate it using the [official go client library](https://prometheus.io/docs/guides/go-application/).

### Why do you need that?

Two reasons:

1. Gaining insights into the adoption and usage of the controller and how it helps teams to improve the [four key metrics](https://cloud.google.com/blog/products/devops-sre/using-the-four-keys-to-measure-your-devops-performance?hl=en).
2. Understand how the controller performs and add monitoring and alerting on top of that

**Comment by AljoschaP** [comment]
If its fine for you @codablock, I would start working on it?

**Comment by codablock** [comment]
@AljoschaP go for it :)

**Comment by AljoschaP** [comment]
Metrics list:

- [x]  Deployment duration (Name, Mode)
- [x]  Prune duration (Name)
- [x]  Validate duration (Name)
- [ ]  Number of changes (Name)
- [ ]  Number of warnings (Name)
- [ ]  Number of errors (Name)
- [ ]  Last status (Name)
- [ ]  ...

**Comment by matzegebbe** [comment]
- [ ] Number of images (from targetConfig) 
- [ ] Prune enabled (Name) 0 | 1
- [ ] Dry-Run enabled  (Name) 0 | 1
