### ISSUE TITLE
Support for pulling helm charts

### ISSUE THREAD

**Issue by linkvt** [kluctl/flux-kluctl-controller#91]
### Controller

- [X] KluctlDeployment

### Who are you?

Vincent, uses kluctl @ home

### What do you want to do?

Hi,

it seems to me that pulling helm charts within the flux kluctl controller is not really supported yet after looking at the docs and the code.
For the version <2.19.0 there also seems to be a bug in the helm charts created `Deployment` due to [`readOnlyRootFilesystem: true`](https://github.com/kluctl/charts/blob/00bff1bffcae3872cba6c468f359005c9b44dd60/charts/flux-kluctl-controller/values.yaml#L35) and the default helm cache dir `/.cache` not being available as an `emptyDir` which I would also fix. 

I guess this the pre-pulling should be configurable in the `KluctlDeployment` which I would happily add in PR if you are open for this contribution?

Best, Vincent

### Why do you need that?

I would like to deploy my kluctl project containing non pre-pulled helm charts with flux.

**Comment by codablock** [comment]
Can you give me more details how you deployed the controller? Did you use the Helm Chart? Did you set `skipPrePull: true` on the affected helm-chart.yaml?

**Comment by linkvt** [comment]
Sure, I deployed the flux kluctl controller via your helm chart. My kluctl project uses helm charts which need to be pulled (currently they are not prepulled, thus `skipPrePull` is not set to `true`).
This means that I need to let the controller pull my helm charts somehow now which is not supported yet.

Let me know if that explains the case, otherwise I can create a sample repo/

**Comment by codablock** [comment]
Can you try to set `skipPrePull: true`? The docs might be unclear on that regard.

The default is to pre-pull Helm Charts. In that case, you are expected to commit the charts to Git, which will also ensure that the controller has the charts available without the need to pull them first. In case you do not want to pre-pull charts, you need to set `skipPrePull: true`, which will then force Kluctl and the Controller to pull while deploying.

**Comment by linkvt** [comment]
That was also my understanding, but I'm getting this error with `skipPrePull: true`, too, with the flux-kluctl-controller v0.14.1:

```
...
* rendering helm chart metallb for release metallb has failed: looks like \"https://metallb.github.io/metallb\" is not a valid chart repository or cannot be reached: open /.cache/helm/repository/A51JqnL18ySmvYBi4xeAQ6Ipvek=-index.yaml: no such file or directory
...
```

The `helm-chart.yml` looks like
```yaml
helmChart:
  repo: https://metallb.github.io/metallb
  chartName: metallb
  chartVersion: 0.13.9
  namespace: metallb
  releaseName: metallb
  skipPrePull: true
```

Are you sure the flux-kluctl-controller does implicitly pull the helm chart if it is not available and `skipPrePull: true` is not set? 
It did do that in the past, although it failed due to `/.cache` being read only in the container which was/is another problem.
Right now my tests show that this doesn't work anymore, but I still might miss something.

I will switch to prepulled charts, but I guess this does not solve this issue.

**Comment by linkvt** [comment]
@codablock thanks, works again as expected!
